-- 合并后的种子文件 (中英严格对应 243 句)
DELETE FROM answer_book;
UPDATE sqlite_sequence SET seq = 0 WHERE name = 'answer_book';

INSERT INTO answer_book (id, dimension, level, content, note, lang) VALUES
(1, 'L', 0, '别在沙滩上盖摩天大楼。稳健的系统，始于你对每一个可能崩掉的边界条件的敬畏。', '针对逻辑边界漏洞', 'cn'),
(2, 'L', 0, '计算机不信星座，Bug 也不吃水逆。建立确定性的第一步，是从肉眼追踪变量流向开始。', '针对“玄学”编程心智', 'cn'),
(3, 'L', 0, '别在逻辑还没闭环的时候就急着加 UI 动效，这就好比地基还没打稳就急着粉刷墙皮。', '针对优先级倒置', 'cn'),
(4, 'L', 0, '任何无法在本地复现的奇迹，本质上都是未被发现的隐患。别信“在我这能跑”这种鬼话。', '针对环境不一致', 'cn'),
(5, 'L', 1, '所谓解耦，就是不要让任何人的离开拖慢你的运行速度。代码如此，人生亦然。', '逻辑解耦哲学', 'cn'),
(6, 'L', 1, '别只修补报错的那一行代码，要修补导致那一行报错的整个思维链路。根治比止痛更重要。', '系统性思维', 'cn'),
(7, 'L', 1, '优雅的代码不是增加出来的，而是删除出来的。每删掉一行冗余，系统的熵就减了一分。', '删减美学', 'cn'),
(8, 'L', 2, '最好的逻辑不是“无懈可击”，而是“一眼见底”。让人一眼看透你的因果，才是顶级玩家。', '极简逻辑', 'cn'),
(9, 'L', 2, '逻辑的终点是美学。当所有冗余消失，代码会呈现出一种平衡的秩序感。', '逻辑美学', 'cn'),
(10, 'L', 2, '代码是人类发明的唯一一种可以自我执行的诗歌。如果它显得臃肿，那是你的韵律乱了。', '代码诗学', 'cn'),
(11, 'P', 0, '没 Git 就敢大改代码？那是赛博跳伞不背降落伞。Commit 是你唯一的后悔药。', '流程安全警示', 'cn'),
(12, 'P', 0, '凌晨三点的“英雄主义”往往是灾难。清醒时的十行代码，胜过修仙时的一百个补丁。', '针对疲劳作业', 'cn'),
(13, 'P', 0, '别跳过本地测试直接推生产。那种心跳加速的感觉不叫激情，那叫职业风险。', '针对流程越级', 'cn'),
(14, 'P', 0, '别想一晚上重构世界。小碎步快跑，比孤注一掷的“大爆炸式更新”要稳如老狗。', '迭代节奏', 'cn'),
(15, 'P', 1, '道理咱都懂，但流程太乱确实伤脑。理顺工作流，其实是在给你的大脑“清缓存”。', '工作流价值', 'cn'),
(16, 'P', 1, '复盘是跟昨天的那个“笨蛋自己”握手言和，并在失败的灰烬里捡出进化的神装。', '复盘意义', 'cn'),
(17, 'P', 1, '开发文档不是写给领导看的，是写给那个三个月后把逻辑忘得精光的你自己。', '文档价值', 'cn'),
(18, 'P', 1, '任务拆得够细，压力就追不上你。把“搬大山”拆成“捡石子”是通关秘籍。', '拆解思维', 'cn'),
(19, 'P', 2, '合理的排期不是为了偷懒，是为了给那些注定会发生的“意外”留出降落伞。', '风险管理', 'cn'),
(20, 'P', 2, '所谓敏捷，不是让你跑得飞快，而是让你在发现跑错方向时，能以最小的代价掉头。', '敏捷真谛', 'cn'),
(21, 'E', 0, '别重复造轮子，除非你确信能造个带涡轮增压的。多去开源社区逛逛，别把自己憋死。', '效率规避', 'cn'),
(22, 'E', 0, '遇事不决查文档。前人踩过的坑都写在那了，咱没必要非得亲自再跳一次火坑。', '查询效率', 'cn'),
(23, 'E', 0, '别在错误的路上狂奔。确保方向正确，比把踏频踩到 120 更有意义。', '方向纠偏', 'cn'),
(24, 'E', 1, '自动化不是为了偷懒，是为了消除人为误差。让机器去做确定性的事，人才有空去搞艺术。', '自动化观', 'cn'),
(25, 'E', 1, '快捷键不是为了装 X，是为了让你的手速能跟上你那跳跃的灵感。', '心流工具', 'cn'),
(26, 'E', 1, '学会拒绝那些没意义的会议。两个小时的扯皮，不如一行能解决问题的代码来得实在。', '时间管理', 'cn'),
(27, 'E', 2, '效率不是写了多少行代码，而是你用多少行代码解决了多大的麻烦。', '效率本质', 'cn'),
(28, 'E', 2, '真正的提效是降低整个系统的认知负荷。让人一眼看穿你的意图，才是最高级的提效。', '长期价值', 'cn'),
(29, 'E', 2, '极简的代码往往是大脑高速旋转后的残余。高端的食材，往往只需要最简单的烹饪方式。', '极致效率', 'cn'),
(30, 'E', 1, '保护你的深度心流。在那一刻，代码不是你敲出来的，是顺着你的指尖流出来的。', '心流状态', 'cn'),
(31, 'D', 0, '起名字是赋予代码灵魂。一个自带语义的变量名，能顶得上三行苍白无力的注释。', '针对命名随意', 'cn'),
(32, 'D', 0, '别总觉得报错是在找茬，它那是看你快掉坑里了，拼了命拽你后腿。细读报错，那是系统给你的情书。', '针对无视错误信息', 'cn'),
(33, 'D', 0, '你的代码逻辑像是一座纸糊的大厦，风一吹全是 undefined。地基（基础类型）得打牢。', '基础不牢告诫', 'cn'),
(34, 'D', 1, '保持好奇心。哪怕是一个简单的 print，背后也藏着操作系统从用户态到内核态的一场宏大叙事。', '深度钻研', 'cn'),
(35, 'D', 1, '理解了内存管理，你才算真正拿到了进入底层世界的入场券。别总在抽象层飘着。', '底层认知进阶', 'cn'),
(36, 'D', 1, '所谓重构，就是给过去的自己“擦屁股”。这活儿虽然脏，但能让你在这个领域真正进化。', '重构成长观', 'cn'),
(37, 'D', 2, '深度思考是好事，但别在没有出口的逻辑里堆栈溢出。记得给自己设个“递归终止条件”。', '深度与边界', 'cn'),
(38, 'D', 2, '只有理解了硬件的极限，你才能写出真正让硬件“高潮”的代码。别只做框架的搬运工。', '软硬结合', 'cn'),
(39, 'D', 2, '每一个 PR 都是一次思维的裸奔。坦然接受 Review，那是别人在帮你查缺补漏。', '开放心态', 'cn'),
(40, 'F', 0, '你得到的模糊结果，是对你模糊初衷的精准惩罚。增加输入熵，别让信号被噪音淹没。', '针对输入简陋', 'cn'),
(41, 'F', 0, '把 AI 当成一个聪明但完全没常识的实习生。如果不给背景，它就只能给你一堆正确的废话。', '上下文缺失', 'cn'),
(42, 'F', 0, '你得到的幻觉，往往是你引导出来的偏见。检查一下你的引导词是不是已经预设了错误的答案？', '针对引导偏见', 'cn'),
(43, 'F', 1, 'Prompt 不是咒语，是契约。你描述得越精确，AI 摸起鱼来就越感到羞愧。', '提问契约感', 'cn'),
(44, 'F', 1, '报错是系统在向你求救，别直接复读给 AI。解读它，并告诉 AI 你当时的真实意图。', '报错处理', 'cn'),
(45, 'F', 1, '给 AI 一个清晰的接口，哪怕你内部混乱得像团乱麻。抽象能力是开发者最后的体面。', '抽象能力', 'cn'),
(46, 'F', 2, '最高级的反馈是人机合一：代码跑通了，你和 AI 都觉得自己在那一瞬间“悟了”。', '心流共振', 'cn'),
(47, 'F', 2, '提问的水平决定了答案的上限。清晰、有约束的输入，是通往赛博心有灵犀的门票。', '沟通高阶技巧', 'cn'),
(48, 'D', 0, '别在核心循环里做昂贵的计算，那是对 CPU 尊严的无视，也是对电费的浪费。', '性能纠偏', 'cn'),
(49, 'E', 0, '现在的“以后再改”，通常就是“永远不改”。技术债有利息，别让未来的你骂现在的自己。', '技术债警示', 'cn'),
(50, 'P', 2, '所谓敏捷，不是让你跑得飞快，而是让你在发现跑错方向时，能以最小的代价掉头。', '敏捷真谛', 'cn'),
(51, 'L', 1, '别只看眼前的一行代码，去理解它背后的数据流动。视野决定了你 Bug 的寿命。', '全局观', 'cn'),
(52, 'D', 0, '别在没有备份的情况下操作生产数据库，那是真正的赛博走钢丝，摔下去就没法 Restart 了。', '高风险行为', 'cn'),
(53, 'E', 1, '自动化部署（CI/CD）是你最好的兄弟。它永远不会因为失恋或者宿醉而忘了打包。', '自动化观', 'cn'),
(54, 'F', 0, '信号越少，噪音就越刺耳。别指望 AI 能通灵，它是逻辑引擎，不是算命先生。', '针对玄学期待', 'cn'),
(55, 'L', 2, '终极的审美是“无”。没有一行多余的变量，没有一个冗长的逻辑，一切皆因必要而存在。', '极简主义', 'cn'),
(56, 'P', 1, '记录下你与 AI 争论的过程。那不只是记录，那是你逻辑边界扩张的真实路径图。', '复盘习惯', 'cn'),
(57, 'D', 1, '所谓架构，就是把复杂的“一团乱麻”理成几个“独立纸箱”。搬家时，你会感谢当初的自己。', '架构洞见', 'cn'),
(58, 'E', 2, '真正的提效是降低整个系统的认知负荷。后来者能一眼看穿你的意图，才是顶级提效。', '长期价值', 'cn'),
(59, 'L', 0, '如果代码跑通了你却不知道为什么，这不叫成功，这叫埋雷。回头去把它搞清楚。', '针对结果侥幸', 'cn'),
(60, 'F', 2, 'AI 是你的外骨骼装甲，不是你的替代品。装甲再强，里面的操作员也得保持清醒。', '人机关系', 'cn'),
(61, 'P', 0, '慌得一批的时候，就回归标准流程。规范不是为了晴天锦上添花，是为了雨天保命。', '针对乱序操作', 'cn'),
(62, 'L', 1, '解耦是最高级的优雅。不要让任何人的离开拖慢你的运行速度，代码和生活都是如此。', '解耦哲学', 'cn'),
(63, 'P', 1, '流程是救生绳。当你迷失在错综复杂的需求里，只有它能带你安全靠岸。', '流程价值', 'cn'),
(64, 'L', 0, '把自己拆分成独立的模块吧。这样即使一个功能崩溃了，你的核心系统依然能硬挺着运行。', '模块化建议', 'cn'),
(65, 'P', 2, '最高级的耐心是克制。在没弄清原委前不轻易落笔，是老手对系统最大的慈悲。', '开发节奏', 'cn'),
(66, 'L', 2, '架构的失败往往源于你试图在第一天，就去解决第一百天才会出现的问题。活在当下。', '过度设计纠偏', 'cn'),
(67, 'P', 0, '拒绝复盘的人，注定要在同一个坑里摔倒第二次。别给历史重演的机会。', '针对不总结', 'cn'),
(68, 'L', 1, '逻辑缺了防线，就只能靠运气撑着。永远假设外部数据是带毒的，加好你的校验码。', '防御性编程', 'cn'),
(69, 'P', 1, '流程是防呆，不是防天才。它能让正确的使用方式变顺手，让错误的方式寸步难行。', '设计哲学', 'cn'),
(70, 'L', 0, '逻辑像空气，当你强烈感觉到它存在时，多半是“窒息”报错了。让它平稳地运行。', '隐形逻辑观', 'cn'),
(71, 'P', 2, '协作的本质是“互不干扰”。好的流程能让你们像并行的多核 CPU，而不是互相死锁。', '并行协作', 'cn'),
(72, 'L', 2, '逻辑自洽是孤独的最高境界。当你不需要任何注释也能讲通因果，你就通关了。', '逻辑审美', 'cn'),
(73, 'P', 0, '欲速则不达。起跑前多花十分钟对齐逻辑，能省下后期三个晚上的通宵排雷。', '针对急躁开发', 'cn'),
(74, 'L', 1, '别在错误的架构上打补丁，那是在给未来的自己挖坟。偶尔需要 Breaking Change 的勇气。', '重构勇气', 'cn'),
(75, 'P', 1, '流程不是枷锁。它是为了让你在摸鱼回来后，还能顺着地图找回刚才断掉的神经。', '工作流恢复', 'cn'),
(76, 'L', 0, '逻辑的终点是闭环。如果你只开了头却没想好收尾，那不叫代码，那叫半成品。', '完备性', 'cn'),
(77, 'P', 2, '留点冗余和缓冲。慢一点是为了让你在撞墙之前，还能优雅地转个身。', '容错哲学', 'cn'),
(78, 'L', 2, '极简的代码往往是大脑高速旋转后的残余。高端的食材，往往只需要最简单的烹饪。', '大道至简', 'cn'),
(79, 'P', 0, '如果你连版本号都管理不好，那你管理的不是代码，而是一堆随机的电子垃圾。', '版本管理意识', 'cn'),
(80, 'L', 1, '架构直觉是磨出来的。多看几种失败的方案，你就能一眼认出那条正确的路。', '架构经验', 'cn'),
(81, 'P', 1, '流程是用来服务创造力的。如果它让你感到窒息，说明这流程已经生锈了。', '流程迭代', 'cn'),
(82, 'L', 0, '别靠直觉写代码。用数据证伪，比用“我感觉”去写需求文档更有尊严。', '客观性', 'cn'),
(83, 'P', 2, '承认失败也是一种智慧。止损并重构，比在烂泥地里盖摩天大楼更高效。', '止损智慧', 'cn'),
(84, 'L', 2, '理解代码背后的流动。向上看业务场景，向下看电子信号。在跨度中寻找灵感。', '全栈视野', 'cn'),
(85, 'P', 0, '没有流程的敏捷叫乱跑。在加速之前，先确保你的方向盘没掉。', '针对伪敏捷', 'cn'),
(86, 'L', 1, '与其死磕代码，不如死磕业务。代码只是手段，解决问题才是终点。', '业务导向', 'cn'),
(87, 'P', 1, '好的流程应该像透明人。你感觉不到它在约束你，但它确实在保护你。', '理想流程观', 'cn'),
(88, 'L', 0, '逻辑崩塌通常始于一个“以后再改”的妥协。守住你的逻辑底线。', '防微杜渐', 'cn'),
(89, 'P', 2, '编程前先画个草图。哪怕只是手绘的，也能在你迷失在细节森林时，带你回家。', '草图价值', 'cn'),
(90, 'L', 2, '最高级的逻辑是自愈。即便环境恶劣，系统也能自己找路回来。', '鲁棒性极致', 'cn'),
(91, 'E', 0, '别在错误的路上狂奔。确保方向正确，比把油门踩到底更重要。校准航向是最高级的提效。', '针对盲目努力', 'cn'),
(92, 'E', 0, '能让机器干的活，人就别瞎掺和。自动化是为了把灵感留给“非你不可”的瞬间。', '自动化意识', 'cn'),
(93, 'E', 1, '关掉那些“叮叮”的推送。深度注意力是这时代最稀缺的 Buff，别被琐事偷走。', '注意力管理', 'cn'),
(94, 'E', 1, '工具决定手速，习惯决定上限。把高频操作变肌肉记忆，才能腾出脑子想架构。', '肌肉记忆', 'cn'),
(95, 'E', 2, '真正的提效是让接手的人少掉两根头发。代码易读，才是对团队最大的效率。', '易读性价值', 'cn'),
(96, 'E', 2, '提效不是转嫁危机。如果你的“快”让后面的人慢得像蜗牛，那不叫效率，叫投机。', '效率道德', 'cn'),
(97, 'F', 0, '别试图用玄学解释代码，也别指望 AI 能通灵。逻辑引擎只吃逻辑，不吃愿望。', '针对非理性期待', 'cn'),
(98, 'F', 0, '如果 AI 给的答案不对，先别急着骂它。回过头看看你的 Prompt，信号是不是断了？', '输入自省', 'cn'),
(99, 'F', 1, '把 AI 当成你的副驾驶，而不是替代品。你可以交出方向盘，但你得盯着航路图。', '人机协作', 'cn'),
(100, 'F', 1, '提问的艺术在于精准。给出一个模糊的锚点，你就只能在茫茫大海里打转。', '提问深度', 'cn'),
(101, 'F', 2, '最高级的反馈是：人机合一。你还没开口，AI 已经根据上下文补全了你最想要的那行逻辑。', '预测性反馈', 'cn'),
(102, 'F', 2, '倾听代码的“沉默”。当它跑不通时，报错信息是你与底层系统唯一的高维对话机会。', '深度反馈观', 'cn'),
(103, 'E', 0, '手动格式化代码是对手指的谋杀。把这些体力活交给 Prettier，把大脑留给逻辑。', '自动化纠偏', 'cn'),
(104, 'E', 1, '别死磕那点微小的性能增益，除非它真的阻碍了用户。先让代码跑得对，再去让它跑得快。', '过早优化警示', 'cn'),
(105, 'E', 2, 'O(1) 的复杂度背后，往往是 O(n) 的思考。在写下第一行代码前，想清楚你的算力分配。', '思考深度', 'cn'),
(106, 'F', 0, '停止向 AI 输入情绪化的废话。它是硅基生命，感知不到你的焦虑，只能感知你的 Token。', '客观沟通', 'cn'),
(107, 'F', 1, '每一次成功的 Prompt 交互，本质上都是一次高效的“思维同步”。确保你们在同一个频道。', '同步思维', 'cn'),
(108, 'F', 2, '学会欣赏 AI 给出的“意外”方案。那不是 Bug，那是它在训练数据海洋里为你捞起的灵感碎片。', '灵感捕捉', 'cn'),
(109, 'E', 0, '别在疲惫时重构核心逻辑。那时候你写的不是代码，是明年春天要修的巨型 Bug。', '效率节奏', 'cn'),
(110, 'E', 1, '善用文档工具，把碎片化的知识固化。大脑是用来处理信息的，不是用来当硬盘存储的。', '第二大脑', 'cn'),
(111, 'F', 0, '给出的反馈越具体，得到的进化就越惊人。别说“不好”，要说“为什么不好”。', '具体化反馈', 'cn'),
(112, 'F', 1, '把复杂的任务拆解成 AI 容易消化的“一口大小”。连 AI 都吞不下去的逻辑，人也读不懂。', '任务拆解', 'cn'),
(113, 'E', 2, '最高级的效率是拒绝。拒绝不合理的需求，拒绝不优雅的代码，拒绝无意义的折腾。', '拒绝的智慧', 'cn'),
(114, 'F', 2, '如果你能准确预测 AI 的下一次回答，说明你的逻辑已经足够清晰，足以主导这场博弈。', '逻辑主导权', 'cn'),
(115, 'E', 0, '别重复昨天的错误。建立自己的“错题本”，同样的坑踩两次是成长，踩三次是算力浪费。', '错误管理', 'cn'),
(116, 'E', 1, '让 AI 帮你写测试代码。这是最划算的交易：你出灵感，它出体力，大家都有美好的未来。', '测试提效', 'cn'),
(117, 'F', 1, '每一次提问都是在塑造 AI 的“人格”。你更倾向于哪种引导，它就会向哪个方向进化。', '引导力', 'cn'),
(118, 'F', 0, '当你开始对 AI 产生盲目崇拜时，就是你逻辑退化的开始。保持警惕，保持怀疑。', '批判性思维', 'cn'),
(119, 'E', 2, '极简意味着极致的控制力。删掉那行你认为“以后可能有用”的代码，现在就删。', '极简行动力', 'cn'),
(120, 'F', 2, '当 AI 给出的方案让你感到被冒犯时，仔细想想：是它错了，还是它戳中了你的知识盲区？', '思维碰撞', 'cn'),
(121, 'D', 0, '起名字是赋予代码灵魂。一个自带语义的变量名，能顶得上三行苍白无力的注释。别用 a, b, c 糊弄你自己。', '针对命名随意', 'cn'),
(122, 'D', 0, '别总觉得报错是在找茬，它那是看你快掉坑里了，拼了命拽你后腿。细读报错，那是系统给你的情书。', '针对无视错误信息', 'cn'),
(123, 'D', 0, '你的代码逻辑像是一座纸糊的大厦，风一吹全是 undefined。地基（基础类型与边界）得打牢。', '针对基础不牢', 'cn'),
(124, 'D', 1, '保持好奇心。哪怕是一个简单的 print，背后也藏着操作系统从用户态到内核态的一场宏大叙事。', '深度钻研', 'cn'),
(125, 'D', 1, '理解了内存管理，你才算真正拿到了进入底层世界的入场券。别总在抽象层飘着，去看看字节是怎么流动的。', '底层认知进阶', 'cn'),
(126, 'D', 1, '所谓重构，就是给过去的自己“擦屁股”。这活儿虽然脏，但能让你在这个领域真正进化。', '重构成长观', 'cn'),
(127, 'D', 2, '深度思考是好事，但别在没有出口的逻辑里堆栈溢出。记得给自己设个“递归终止条件”。', '深度与边界', 'cn'),
(128, 'D', 2, '只有理解了硬件的极限，你才能写出真正让硬件“高潮”的代码。别只做框架的搬运工。', '软硬结合', 'cn'),
(129, 'D', 2, '每一个 PR 都是一次思维的裸奔。坦然接受 Review，那是别人在帮你的逻辑“修枝剪叶”。', '开放心态', 'cn'),
(130, 'L', 0, '如果代码跑通了你却不知道为什么，这不叫成功，这叫埋雷。回头去把它搞清楚，否则雷迟早会炸。', '针对结果侥幸', 'cn'),
(131, 'L', 0, '别在逻辑还没闭环时就急着优化性能。在错误的道路上跑得越快，你离终点就越远。', '优先级纠偏', 'cn'),
(132, 'L', 1, '别只看眼前的一行代码，去理解它背后的数据流动。视野决定了你 Bug 的寿命。', '全局观', 'cn'),
(133, 'L', 1, '优雅的代码不是增加出来的，而是删除出来的。每删掉一行冗余，系统的熵就减了一分。', '删减美学', 'cn'),
(134, 'L', 2, '终极的审美是“无”。没有一行多余的变量，没有一个冗长的逻辑，一切皆因必要而存在。', '极简主义', 'cn'),
(135, 'L', 2, '逻辑自洽是孤独的最高境界。当你不需要任何注释也能讲通因果，你就通关了。', '逻辑审美', 'cn'),
(136, 'D', 0, '别在核心循环里做昂贵的计算，那是对 CPU 尊严的无视。请尊重每一颗时钟周期的心跳。', '性能纠偏', 'cn'),
(137, 'D', 1, '去读读源码。那是前人留下的地图，虽然路况复杂，但能带你避开那些注定会撞墙的死胡同。', '源码修行', 'cn'),
(138, 'D', 2, '真正的深度不是钻牛角尖，是能从一个简单的报错，联想到整个操作系统的资源调度逻辑。', '深度联想力', 'cn'),
(139, 'L', 1, '别在错误的架构上打补丁，那是在给未来的自己挖坟。偶尔需要 Breaking Change 的勇气。', '重构勇气', 'cn'),
(140, 'L', 0, '逻辑崩塌通常始于一个“以后再改”的妥协。守住你的逻辑底线，那是你最后的防线。', '防微杜渐', 'cn'),
(141, 'D', 1, '所谓架构，就是把复杂的“一团乱麻”理成几个“独立纸箱”。搬家时，你会感谢当初的自己。', '架构洞见', 'cn'),
(142, 'D', 0, '别在没有备份的情况下操作生产数据库，那是真正的赛博走钢丝，摔下去就没法 Restart 了。', '针对高风险行为', 'cn'),
(143, 'L', 2, '代码是人类发明的唯一一种可以自我执行的诗歌。如果它显得臃肿，那是你的韵律乱了。', '代码诗学', 'cn'),
(144, 'L', 0, '逻辑的终点是闭环。如果你只开了头却没想好收尾，那不叫代码，那叫半成品。', '完备性', 'cn'),
(145, 'D', 2, '极致的性能优化往往伴随着极致的认知成本。你要想清楚，你的业务到底值不值得你如此“压榨”机器。', '性能权衡', 'cn'),
(146, 'L', 1, '解耦是最高级的优雅。不要让任何人的离开拖慢你的运行速度，代码和生活都是如此。', '解耦哲学', 'cn'),
(147, 'D', 1, '理解代码背后的流动。向上看业务场景，向下看电子信号。在跨度中寻找灵感。', '全栈视野', 'cn'),
(148, 'L', 2, '最高级的逻辑是自愈。即便环境恶劣，系统也能自己找路回来。这是代码的求生本能。', '鲁棒性极致', 'cn'),
(149, 'D', 0, '对基础库的盲目信任是灾难的温床。偶尔去看看它们的实现，别被表面的 API 给骗了。', '去盲从化', 'cn'),
(150, 'L', 1, '架构直觉是磨出来的。多看几种失败的方案，你就能一眼认出那条正确的路。', '架构经验', 'cn'),
(151, 'P', 0, '别跳过本地测试直接推送到生产环境。那种“心跳加速”不叫激情，叫对职业生涯的博弈。稳住，别浪。', '针对流程越级', 'cn'),
(152, 'P', 0, '没有备份的操作就像是在火山口跳舞。在按下那个确定键之前，先问问自己：如果崩了，我有退路吗？', '针对安全意识匮乏', 'cn'),
(153, 'P', 1, '开发文档不是写给领导看的，是写给那个三个月后把这段逻辑忘得精光的你自己。救救未来的你吧。', '文档价值', 'cn'),
(154, 'P', 1, '需求变更是常态，别急着摔键盘。把架构写灵活点，才是你对产品经理最深沉的温柔（和反击）。', '应对变更', 'cn'),
(155, 'P', 2, '合理的排期不是为了偷懒，是为了给那些注定会发生的“意外”留出降落伞。学会预留 buffer。', '风险管理', 'cn'),
(156, 'P', 2, '所谓敏捷开发，不是让你跑得飞快，而是让你在发现跑错方向时，能以最小的掉头半径转身。', '敏捷真谛', 'cn'),
(157, 'E', 0, '别重复造轮子，除非你确信能造个带涡轮增压的。多去开源社区逛逛，前人已经帮你解决了一半的麻烦。', '避免无效自研', 'cn'),
(158, 'E', 0, '快捷键不是为了装 X，是为了让你的手速能跟上你那跳跃的灵感。把高频操作磨练成肌肉记忆。', '工具熟练度', 'cn'),
(159, 'E', 1, '屏蔽那些没用的干扰。心流一旦断了，重连的代价比服务器断网重启还要贵，那是灵魂的带宽。', '心流保护', 'cn'),
(160, 'E', 1, '能用一行代码说清楚的事，别写十行。效率的真谛不仅在于产出，更在于对复杂性的克制。', '克制提效', 'cn'),
(161, 'E', 2, '真正的效率高手，都懂得在“完美”与“完成”之间找平衡。追求极致是艺术，按时交付是生存。', '效率平衡', 'cn'),
(162, 'E', 2, '把高频的垃圾活儿自动化。你节省的每一分钟，都是在为你的下一个伟大构思攒时间。', '自动化思维', 'cn'),
(163, 'P', 0, '每一个 PR 都是一次思维的裸奔。坦然接受别人的 Code Review，那是别人在帮你查缺补漏。', '针对排外心态', 'cn'),
(164, 'P', 1, '流程不是为了限制高手，是为了保住底线。它能确保在大家都疲惫不堪时，系统依然能体面地运行。', '流程底线', 'cn'),
(165, 'P', 2, '自动化部署（CI/CD）是你最好的兄弟。它永远不会因为失恋或者宿醉而忘了帮你打包上线。', '工程化进阶', 'cn'),
(166, 'E', 0, '别在错误的架构上狂奔。如果你发现自己写代码越来越累，多半是方向错了，停下来校准。', '针对低效执行', 'cn'),
(167, 'E', 1, '好的 IDE 是你的半条命。舍得在工具配置上花时间的人，最后都能在敲代码时省出休息时间。', '生产力工具', 'cn'),
(168, 'E', 2, '极致的效率源于对问题的深刻拆解。把“搬大山”拆成“捡石子”，压力就追不上你。', '任务拆解', 'cn'),
(169, 'P', 1, 'Commit 留言写清楚点。别让一年后的你看到这行代码时，产生想要报警抓当初那个自己的冲动。', '规范意识', 'cn'),
(170, 'P', 0, '任务管理不是为了记账，是为了清空大脑缓存。把待办写下来，大脑才能全神贯注处理逻辑。', '内存管理哲学', 'cn'),
(171, 'E', 1, '保持对新技术的敏锐，但别当框架的舔狗。所有的工具都是为了解决问题，别本末倒置。', '技术观平衡', 'cn'),
(172, 'E', 2, '当你感觉代码是“流”出来而不是“抠”出来的时候，恭喜你，你已经进入了开发者的神性时刻。', '极致心流', 'cn'),
(173, 'P', 0, '别试图通过通宵来掩盖流程的缺失。早睡早起理顺工作流，比喝十罐红牛都有用。', '针对作息乱象', 'cn'),
(174, 'P', 1, '每一个被解决的 Bug 都该成为你知识库的一块砖。别只是修复它，要内化它，让它别再回来。', '经验内化', 'cn'),
(175, 'P', 2, '高阶玩家的标志是：即使环境混乱，我也能通过一套稳定的流程，产出确定性的结果。', '确定性产出', 'cn'),
(176, 'E', 0, '拒绝那些没意义的会议。如果一个问题能用三行代码演示清楚，就别用一个小时开会讨论。', '反会议文化', 'cn'),
(177, 'E', 1, '学会搜索，更要学会过滤。在信息爆炸的时代，找到那条正确的答案本身就是一种核心竞争力。', '信息检索力', 'cn'),
(178, 'E', 2, '提效的终极奥义是“不写”。能用现成逻辑解决的，坚决不手写。不产出代码才是最稳的代码。', '极简哲学', 'cn'),
(179, 'P', 1, '流程是用来迭代的。如果它让你感到痛苦，那就重构它，就像重构你那臃肿的 controller 一样。', '流程进化', 'cn'),
(180, 'P', 0, '别在没写单测的情况下重构核心逻辑。那是赛步盲跑，你根本不知道哪一步会踩空。', '针对风险重构', 'cn'),
(181, 'F', 0, '不要向未授权的对象开放你内心的私有变量（Private）。在对话中守住你的核心逻辑，别被 AI 的发散带偏了。', '针对沟通无边界', 'cn'),
(182, 'F', 0, '提示词越清晰，结局越笃定。如果你总是在得到错误的答案，先检查一下你是否给出了含糊的指令。', '输入确定性', 'cn'),
(183, 'F', 1, '守住你的 System Prompt，那是你作为独立开发者最后的底线。不要让临时的业务需求污染了你的底层架构。', '底线思维', 'cn'),
(184, 'F', 1, '给世界一个清晰的接口，哪怕你内部混乱得像团乱麻。对外保持秩序感，是高阶反馈的艺术。', '抽象与封装', 'cn'),
(185, 'F', 2, '每一次成功的 Prompt 交互，都是一次思维的“量子纠缠”。当你能精准预判它的输出，说明你的逻辑已经降维打击了。', '反馈高阶控制', 'cn'),
(186, 'L', 0, '与其在错误的架构上打补丁，不如直接执行一次彻底的重构。止损的勇气，往往比坚持的韧性更重要。', '重构决断力', 'cn'),
(187, 'L', 0, '任何无法扩展的逻辑，本质上都是在给未来挖坑。别为了当下的“省事”，断了以后的“活路”。', '扩展性警示', 'cn'),
(188, 'L', 1, '即使代码能跑，也要问问自己：这个逻辑真的优雅吗？在计算机的世界里，美感通常意味着更低的维护成本。', '代码审美', 'cn'),
(189, 'L', 1, '强行兼容会让你背负沉重的历史包袱，偶尔需要一次 Breaking Change 来实现真正的轻装上阵。', '断舍离', 'cn'),
(190, 'L', 2, '把复杂的系统拆解成原子级的逻辑。当你掌握了原子，你就掌握了重组整个赛博世界的权力。', '原子化思维', 'cn'),
(191, 'D', 0, '别只看 UI 表面的光鲜。如果底层逻辑是屎山，再华丽的交互也掩盖不了随时可能崩溃的本质。', '针对表面工程', 'cn'),
(192, 'D', 0, '对基础协议的无知，是所有“高级错误”的源头。回头去看看 TCP 是怎么握手的，看看 HTTP 是怎么解析的。', '协议敬畏', 'cn'),
(193, 'D', 1, '深度不是为了炫技，是为了在遇到那个“百万分之一”级别的 Bug 时，你能比别人更快定位到那行关键代码。', '深度的实用价值', 'cn'),
(194, 'D', 1, '变量命名中的“缩写”是毒药。除非是公认的标准，否则请用全拼，那是对后来者阅读时间的尊重。', '命名细节', 'cn'),
(195, 'D', 2, '每一个字节的分配都应该深思熟虑。在大算力时代，这种“抠门”正是区分匠人与码农的分水岭。', '匠人心态', 'cn'),
(196, 'F', 0, '反馈不是复读机。如果 AI 只是在重复你的错误，说明你的反馈回路已经失效了，需要重新初始化环境。', '反馈回路修正', 'cn'),
(197, 'F', 1, '试着向 AI 解释你的“为什么”而不只是“怎么做”。当它理解了你的动机，它给出的方案会带上灵魂。', '动机驱动沟通', 'cn'),
(198, 'F', 2, '最好的 Prompt 是无声的。通过高质量的上下文堆叠，让 AI 在潜移默化中成为最懂你的影子开发者。', '上下文沉淀', 'cn'),
(199, 'L', 0, '不要迷信单一的算法。如果业务逻辑本身是扭曲的，再精妙的排序也排不出正确的人生。', '逻辑本位论', 'cn'),
(200, 'L', 1, '在逻辑分支中预留“逃生舱”。当所有的 case 都没命中时，至少给系统一个体面的 fallback。', '容错设计', 'cn'),
(201, 'D', 1, '所谓老手，就是那个见过一万种报错姿势后，依然能对第 10001 种报错保持兴奋的家伙。', '职业热情', 'cn'),
(202, 'D', 2, '深挖底层逻辑，不是为了留在底层，而是为了在构建高层建筑时，地基能承载住你狂野的想象力。', '底层支撑', 'cn'),
(203, 'E', 0, '别在还没理解需求时就开始敲代码。那是对手指的损耗，也是对大脑算力的犯罪。', '效率预警', 'cn'),
(204, 'E', 1, '工具是手的延伸。花时间调优你的 IDE 插件，就像剑客花时间磨他的剑一样，这不叫浪费时间。', '工具观', 'cn'),
(205, 'E', 2, '效率的极致是“自动化一切重复”。如果你发现自己在一周内做了三次相同的操作，写个脚本杀掉它。', '自动化决断', 'cn'),
(206, 'P', 0, '没有文档的代码是不可维护的“黑盒”。别指望别人能通灵，也别指望半年后的你能记起今天的意图。', '文档缺失预警', 'cn'),
(207, 'P', 1, '流程是经验的凝固。尊重那些看似繁琐的 Checkpoint，它们是无数次事故后留下的安全带。', '流程敬畏', 'cn'),
(208, 'P', 2, '最好的流程是“无感”的。当你的工作流已经顺滑到像呼吸一样自然，你就达到了工程化的巅峰。', '理想工作流', 'cn'),
(209, 'L', 1, '分治法（Divide and Conquer）不仅是算法，更是解决复杂人生问题的万能公式。拆了它，解决它。', '分治思想', 'cn'),
(210, 'D', 0, '别被各种花哨的新名词骗了。剥开那层皮，底层逻辑还是那几样。练好基本功，你就能以不变应万变。', '基本功重申', 'cn'),
(211, 'P', 1, '别在还没复盘前就开启下一个 Sprint。不带经验的冲刺，只是在低水平的勤奋里反复消耗。', '复盘进阶', 'cn'),
(212, 'L', 2, '最好的架构是那种能让人忘记它存在的架构。它像呼吸一样自然，支撑着一切却从不喧宾夺主。', '架构最高境界', 'cn'),
(213, 'E', 1, '别让你的工具箱生锈。定期更新你的技术栈，不是为了追时髦，是为了确保你手里的武器还能杀敌。', '持续进化', 'cn'),
(214, 'D', 1, '对代码的敬畏心，始于你意识到每一行逻辑都可能在未来的某个深夜，成为压死骆驼的最后一根稻草。', '敬畏心', 'cn'),
(215, 'F', 1, '学会拒绝 AI 给出的平庸方案。你有权要求更好的逻辑，前提是你能定义什么是“更好”。', '主导权', 'cn'),
(216, 'L', 0, '逻辑上的“想当然”是万恶之源。去验证它，哪怕是用最笨的 print 调试法，也比空想强。', '实证主义', 'cn'),
(217, 'P', 2, '耐心不是等待，而是在等待的过程中保持清醒。在代码编译的间隙，思考你的下一步退路。', '耐心真谛', 'cn'),
(218, 'E', 2, '极致的效率是“认知杠杆”。用少量的底层认知，撬动复杂的应用层逻辑。这叫四两拨千斤。', '认知杠杆', 'cn'),
(219, 'D', 0, '不要在不懂原理的情况下粘贴代码。你粘贴的不只是逻辑，还有可能是一个你理解不了的定时炸弹。', '反粘贴工程', 'cn'),
(220, 'F', 1, '好的沟通是“有借有还”。你给 AI 一个精准的背景，它还你一个优雅的模块。这叫双向奔赴。', '沟通平衡', 'cn'),
(221, 'L', 1, '如果你发现逻辑绕不回来了，就跳出来看看。当局者迷，旁观者清。换个维度思考往往就通了。', '思维跳出', 'cn'),
(222, 'P', 1, '别让进度压力杀死了你的工程质量。今天的“快”，就是明天的“坑”。守住你的底线。', '质量守恒', 'cn'),
(223, 'E', 0, '效率的杀手是“多任务并行”。大脑不是多核 CPU，上下文切换的开销会让你颗粒无收。', '串行工作哲学', 'cn'),
(224, 'D', 2, '理解抽象，但别迷失在抽象里。任何高阶的模式，最终都要回归到最朴素的数据存取。', '回归本质', 'cn'),
(225, 'F', 2, '最高级的反馈是不言而喻。当你和系统的交互达到一种默契时，代码已经成了你们共同的语言。', '交互极致', 'cn'),
(226, 'L', 2, '架构的失败往往源于你试图在第一天，就去解决第一百天才会出现的问题。学会延迟决策。', '延迟决策', 'cn'),
(227, 'P', 0, '别在情绪化的时候写代码。那时候你产出的不是逻辑，而是充满戾气的技术债。', '情绪管理', 'cn'),
(228, 'E', 1, '学会利用 AI 的发散性，但要用你的确定性去约束它。灵感需要边界才能转化为生产力。', '灵感边界', 'cn'),
(229, 'D', 1, '所谓老手，就是那个能在一堆看似完美的逻辑中，一眼嗅出“腐烂味”的家伙。', '技术嗅觉', 'cn'),
(230, 'F', 0, '别把 AI 的客气当真。它只是个概率模型，它的“好的”后面可能跟着一堆乱码。保持警惕。', '去魅化', 'cn'),
(231, 'L', 1, '每一个复杂的 Bug 背后，都藏着一个你没看透的简单真理。把它找出来。', '化繁为简', 'cn'),
(232, 'P', 2, '最好的复盘是“事前验尸”。在项目开始前，先想好一百种它可能死掉的方式。', '风险前置', 'cn'),
(233, 'E', 2, '效率的最高境界是“不劳而获”。通过极致的复用和抽象，让后续的功能自动生长出来。', '生长式架构', 'cn'),
(234, 'D', 0, '别把“复杂”当成“高级”。真正的天才，是能把极其复杂的事情，用三岁小孩都能听懂的话讲清楚。', '反对复杂化', 'cn'),
(235, 'F', 1, '把你的代码当成产品去交付。即便是给 AI 看的，也要保持那份应有的仪式感。', '职业尊严', 'cn'),
(236, 'L', 0, '逻辑崩塌通常始于一个“以后再改”的妥协。守住你的逻辑底线，那是你最后的防线。', '防微杜渐', 'cn'),
(237, 'P', 1, '流程是经验的凝固。尊重那些看似繁琐的 Checkpoint，它们是无数次事故后留下的安全带。', '流程敬畏', 'cn'),
(238, 'E', 0, '别重复昨天的错误。建立自己的“错题本”，同样的坑踩两次是成长，踩三次是算力浪费。', '错误管理', 'cn'),
(239, 'D', 2, '终极的审美是“空”。没有一行多余的变量，没有一个冗长的逻辑，一切皆因必要而存在。', '极简哲学', 'cn'),
(240, 'F', 2, '当 AI 给出的方案让你感到被冒犯时，仔细想想：是它错了，还是它戳中了你的知识盲区？', '思维碰撞', 'cn'),
(241, 'L', 2, '所谓高阶架构，不是为了炫技，而是为了让系统在最极端的压力下，依然能保持呼吸的频率。稳健，是最高级的审美。', '架构终极内功', 'cn'),
(242, 'D', 2, '代码的最高境界是“空”：没有一行多余的变量，没有一个冗长的逻辑，一切皆因必要而存在。在繁琐的世界里守住极简。', '极致细腻审美', 'cn'),
(243, 'P', 2, '初心不是终点，而是你每次想放弃时，那个让你重新打开控制台的微弱火光。保护好它，它是你唯一的燃料。', '职业初心压轴', 'cn'),
(244, 'L', 0, 'Don’t build skyscrapers on shifting sands. Robust systems start with a healthy fear of edge cases.', 'Logic boundary awareness', 'en'),
(245, 'L', 0, 'Computers don’t care about your horoscope, and bugs don’t care about Mercury retrograde. Trust the data flow, not the vibes.', 'Deterministic programming', 'en'),
(246, 'L', 0, 'Don’t polish the UI before the logic is closed. That’s like painting the walls before the foundation is poured.', 'Priority inversion', 'en'),
(247, 'L', 0, 'A miracle that can''t be reproduced locally is just a ticking time bomb. Never trust "it works on my machine."', 'Environment consistency', 'en'),
(248, 'L', 1, 'True decoupling means no single person’s departure slows down the system. True for code, truer for life.', 'Decoupling philosophy', 'en'),
(249, 'L', 1, 'Don’t just fix the line that threw the error; fix the thought process that wrote it. Cure the disease, not the symptom.', 'Systems thinking', 'en'),
(250, 'L', 1, 'Elegant code isn''t achieved by adding features, but by removing them. Every deleted line reduces the system’s entropy.', 'Minimalist aesthetics', 'en'),
(251, 'L', 2, 'The best logic isn''t "unbreakable"—it’s "obvious." If a junior can''t see the cause and effect at a glance, you''ve over-engineered it.', 'Simplicity in logic', 'en'),
(252, 'L', 2, 'The endgame of logic is aesthetics. When all redundancy is gone, what remains is an inevitable sense of order.', 'Logic as art', 'en'),
(253, 'L', 2, 'Code is the only form of poetry that executes itself. If it feels bloated, your rhythm is off.', 'Code poetics', 'en'),
(254, 'P', 0, 'Changing code without Git? That’s skydiving without a parachute. Commit early, commit often—it''s your only undo button.', 'Workflow safety', 'en'),
(255, 'P', 0, '3 AM "heroics" are usually disasters in disguise. Ten lines written while sober beat a hundred patches written while sleep-deprived.', 'Anti-crunch culture', 'en'),
(256, 'P', 0, 'Pushing to production without local testing isn''t "passion"; it''s a professional liability. Watch your heart rate.', 'Process bypass risk', 'en'),
(257, 'P', 0, 'Don''t try to refactor the world in one night. Small, steady steps beat a "Big Bang" update every time.', 'Iteration rhythm', 'en'),
(258, 'P', 1, 'A messy process drains your CPU. Streamlining your workflow is just "clearing the cache" for your brain.', 'Workflow value', 'en'),
(259, 'P', 1, 'Post-mortems are about making peace with your "past idiot self" and finding legendary loot in the ashes of failure.', 'Value of retrospectives', 'en'),
(260, 'P', 1, 'Docs aren''t for your boss. They’re for the version of you three months from now who will have zero clue how this works.', 'Documentation as self-care', 'en'),
(261, 'P', 1, 'If the task is small enough, the pressure can''t catch you. Moving a mountain is just picking up one stone at a time.', 'Decomposition strategy', 'en'),
(262, 'P', 2, 'A good schedule isn''t for laziness; it’s a buffer for the "unexpected" disasters that are statistically guaranteed to happen.', 'Risk management', 'en'),
(263, 'P', 2, 'Agile isn''t about running fast; it''s about being able to pivot with minimal cost when you realize you''re running the wrong way.', 'True agility', 'en'),
(264, 'E', 0, 'Don’t reinvent the wheel unless you’re planning to add a turbocharger. Browse GitHub; don''t suffer in isolation.', 'Avoiding NIH syndrome', 'en'),
(265, 'E', 0, 'When in doubt, RTFM. Someone has already fallen into this pit; you don''t need to experience the fire personally.', 'Information retrieval', 'en'),
(266, 'E', 0, 'Running at 120mph is useless if you''re heading off a cliff. Direction > Speed.', 'Course correction', 'en'),
(267, 'E', 1, 'Automation isn''t for laziness; it''s for eliminating human error. Let machines handle the mundane so you can handle the art.', 'Automation mindset', 'en'),
(268, 'E', 1, 'Hotkeys aren''t for showing off; they''re to ensure your hands can keep up with the speed of your inspiration.', 'Flow state tools', 'en'),
(269, 'E', 1, 'Learn to decline useless meetings. Two hours of yapping is rarely worth one line of code that actually works.', 'Time management', 'en'),
(270, 'E', 2, 'Efficiency isn''t about how many lines you wrote, but how much trouble you solved with the lines you kept.', 'Essence of efficiency', 'en'),
(271, 'E', 2, 'Real efficiency is lowering the cognitive load of the entire system. If others can read your intent instantly, you’ve won.', 'Long-term value', 'en'),
(272, 'E', 2, 'Minimalist code is the residue of a high-speed mind. The best ingredients only need the simplest preparation.', 'Extreme efficiency', 'en'),
(273, 'E', 1, 'Protect your flow state. In that moment, the code isn''t being typed; it''s flowing through your fingertips.', 'Flow state protection', 'en'),
(274, 'D', 0, 'Naming things is breathing soul into code. A semantic variable name is worth more than three lines of hollow comments.', 'Against sloppy naming', 'en'),
(275, 'D', 0, 'Don’t treat errors like insults. They are the system trying to pull you back from a cliff. Read them like love letters.', 'Error message appreciation', 'en'),
(276, 'D', 0, 'Your logic is a paper skyscraper, and the wind is blowing "undefined." Fix your foundation (primitive types) first.', 'Weak fundamentals', 'en'),
(277, 'D', 1, 'Stay curious. Even a simple "print" statement hides a grand narrative of context switching from user space to kernel space.', 'Deep exploration', 'en'),
(278, 'D', 1, 'Understanding memory management is your ticket to the basement of reality. Stop floating in the abstractions.', 'Low-level awareness', 'en'),
(279, 'D', 1, 'Refactoring is just cleaning up after your "past self." It’s dirty work, but it’s how you actually evolve.', 'Growth through refactoring', 'en'),
(280, 'D', 2, 'Deep thinking is great, but don''t stack-overflow in a logic loop with no exit. Always set a recursion limit for your brain.', 'Depth and boundaries', 'en'),
(281, 'D', 2, 'Only when you understand the limits of the hardware can you write code that makes the silicon sing.', 'Hardware-software synergy', 'en'),
(282, 'D', 2, 'Every Pull Request is a form of intellectual streaking. Accept the Review; it’s someone helping you find your blind spots.', 'Open mindset', 'en'),
(283, 'F', 0, 'The vague results you get are the precise punishment for your vague intentions. Cut the noise; increase the entropy.', 'Input quality control', 'en'),
(284, 'F', 0, 'Treat AI like a brilliant intern with zero common sense. Without context, it will only give you confident nonsense.', 'Context loss', 'en'),
(285, 'F', 0, 'The "hallucinations" you see are often just your own biases reflected back at you. Check your prompts for loaded questions.', 'Prompt bias', 'en'),
(286, 'F', 1, 'A prompt isn''t a magic spell; it’s a contract. The more precise the terms, the less room there is for the AI to slack off.', 'The prompt contract', 'en'),
(287, 'F', 1, 'Errors are the system screaming for help. Don''t just copy-paste them to AI—explain what you were trying to achieve.', 'Error handling', 'en'),
(288, 'F', 1, 'Provide a clean interface to the world, even if your internal logic is a ball of yarn. Abstraction is a developer''s dignity.', 'Abstraction power', 'en'),
(289, 'F', 2, 'The highest form of feedback is "Human-Machine Resonance": the code works, and both you and the AI feel "enlightened."', 'Flow resonance', 'en'),
(290, 'F', 2, 'The quality of your questions sets the ceiling for the answers. Precision is your ticket to cyber-telepathy.', 'Communication mastery', 'en'),
(291, 'D', 0, 'Don’t run expensive calculations in a core loop. It’s an insult to the CPU and a crime against the battery.', 'Performance correction', 'en'),
(292, 'E', 0, '"Fix it later" usually means "never." Technical debt has high interest—don''t let your future self hate you.', 'Technical debt warning', 'en'),
(293, 'P', 2, 'Agility isn''t about moving fast; it’s about having a small enough turning radius to pivot when you hit a dead end.', 'Essence of Agile', 'en'),
(294, 'L', 1, 'Look past the line of code to the data flow behind it. Your vision determines the lifespan of your bugs.', 'Global perspective', 'en'),
(295, 'D', 0, 'Operating on a production DB without a backup is cyber tightrope walking. There is no "Restart" after a fall.', 'High-risk behavior', 'en'),
(296, 'E', 1, 'CI/CD is your best friend. It won''t forget to run a build because of a breakup or a hangover.', 'Automation value', 'en'),
(297, 'F', 0, 'The less signal you provide, the louder the noise. AI is a logic engine, not a crystal ball.', 'Against mystical expectations', 'en'),
(298, 'L', 2, 'The ultimate aesthetic is "Nothing." No extra variables, no redundant logic—everything exists only because it is necessary.', 'Maximalist minimalism', 'en'),
(299, 'P', 1, 'Log your arguments with the AI. That’s not just a record; it’s a map of your own logical expansion.', 'Reflection habits', 'en'),
(300, 'D', 1, 'Architecture is taking a "mess of yarn" and putting it into "labeled boxes." You''ll thank yourself when it''s time to move.', 'Architectural insight', 'en'),
(301, 'E', 2, 'Real efficiency is reducing the cognitive load for the next person. If they can see your intent instantly, you’re a pro.', 'Long-term value', 'en'),
(302, 'L', 0, 'If the code works and you don’t know why, that’s not success—it’s a landmine. Go back and figure it out.', 'Against lucky results', 'en'),
(303, 'F', 2, 'AI is your exoskeleton, not your replacement. No matter how strong the suit, the pilot still needs to stay awake.', 'Human-AI relationship', 'en'),
(304, 'P', 0, 'When everything is going south, return to the standard procedure. Protocols aren''t for sunny days; they are for survival in the rain.', 'Against chaotic operations', 'en'),
(305, 'L', 1, 'Decoupling is the highest form of elegance. Don''t let anyone''s departure slow down your execution—in code and in life.', 'Decoupling philosophy', 'en'),
(306, 'P', 1, 'The process is your lifeline. When you’re lost in a jungle of requirements, only the workflow can lead you back to shore.', 'Value of process', 'en'),
(307, 'L', 0, 'Build yourself like a modular system. Even if one function crashes, the core should remain standing.', 'Modularity advice', 'en'),
(308, 'P', 2, 'The ultimate patience is restraint. Not writing a single line before you understand the "why" is the greatest mercy you can show a system.', 'Development rhythm', 'en'),
(309, 'L', 2, 'Architectural failure usually stems from trying to solve Day 100 problems on Day 1. Live in the now.', 'Against over-engineering', 'en'),
(310, 'P', 0, 'Those who refuse to debrief are doomed to fall into the same pit twice. Don''t give history a chance to repeat itself.', 'Against lack of summary', 'en'),
(311, 'L', 1, 'Logic without a defensive line relies on luck. Always assume external data is toxic; add your validation.', 'Defensive programming', 'en'),
(312, 'P', 1, 'Process is about "idiot-proofing," not "genius-blocking." It makes the right way easy and the wrong way impossible.', 'Design philosophy', 'en'),
(313, 'L', 0, 'Logic is like air; you only notice it when it’s suffocating you. Let it run silently in the background.', 'Invisible logic', 'en'),
(314, 'P', 2, 'The essence of collaboration is "non-interference." A good process makes you look like parallel CPU cores rather than a deadlock.', 'Parallel collaboration', 'en'),
(315, 'L', 2, 'Logical self-consistency is a lonely peak. When you no longer need comments to explain cause and effect, you’ve won.', 'Logic aesthetics', 'en'),
(316, 'P', 0, 'Haste makes waste. Ten minutes aligning logic before you start can save three nights of midnight debugging.', 'Against rushed development', 'en'),
(317, 'L', 1, 'Don’t patch a broken architecture; that’s just digging a grave for your future self. Occasionally, you need the courage for a Breaking Change.', 'Refactoring courage', 'en'),
(318, 'P', 1, 'Process isn’t a cage. It’s a map so that when you come back from a break, you can find the nerve endings you dropped.', 'Workflow recovery', 'en'),
(319, 'L', 0, 'The end of logic is a closed loop. If you only start things without finishing the "else" case, it’s not code—it’s a fragment.', 'Completeness', 'en'),
(320, 'P', 2, 'Leave some room for redundancy and buffers. Moving slower allows you to turn gracefully before you hit the wall.', 'Fault-tolerance philosophy', 'en'),
(321, 'L', 2, 'Minimalist code is the residue of high-intensity thinking. The finest ingredients require the simplest cooking.', 'Grand simplicity', 'en'),
(322, 'P', 0, 'If you can''t manage version numbers, you aren''t managing code—you''re managing a pile of random electronic garbage.', 'Version control awareness', 'en'),
(323, 'L', 1, 'Architectural intuition is forged in fire. Study enough failed designs, and you’ll recognize the right path instantly.', 'Architectural experience', 'en'),
(324, 'P', 1, 'The process should serve creativity. If it makes you feel suffocated, the process itself is rusted and needs refactoring.', 'Process iteration', 'en'),
(325, 'L', 0, 'Don’t code on vibes. Proving yourself wrong with data is more dignified than saying "I feel like" in a PR.', 'Objectivity', 'en'),
(326, 'P', 2, 'Admitting failure is wisdom. Cutting your losses to refactor is more efficient than building a skyscraper in a swamp.', 'Wisdom of stopping loss', 'en'),
(327, 'L', 2, 'Understand the flow behind the code. Look up at the business scene and down at the electronic signals. Find inspiration in the span.', 'Full-stack vision', 'en'),
(328, 'P', 0, 'Agility without process is just running in circles. Before you accelerate, make sure the steering wheel is attached.', 'Against pseudo-agility', 'en'),
(329, 'L', 1, 'Instead of fighting the code, fight the business logic. Code is just the means; solving the problem is the destination.', 'Business-oriented', 'en'),
(330, 'P', 1, 'A good process should be invisible. You shouldn''t feel it constraining you, but you should know it’s protecting you.', 'Ideal process', 'en'),
(331, 'L', 0, 'Logical collapse usually starts with a "fix it later" compromise. Guard your logical boundaries.', 'Nip it in the bud', 'en'),
(332, 'P', 2, 'Sketch it out before you code. Even a rough drawing can lead you home when you’re lost in a forest of details.', 'Value of sketching', 'en'),
(333, 'L', 2, 'The highest form of logic is self-healing. A truly robust system doesn''t just resist failure; it embraces it, isolates it, and finds its own way back to equilibrium.', 'Resilience & Self-healing Philosophy', 'en'),
(334, 'E', 0, 'If a machine can do it, a human shouldn''t. Automation exists to save your inspiration for the moments where "only you" will do.', 'Automation awareness', 'en'),
(335, 'E', 1, 'Turn off the "ping" notifications. Deep focus is the rarest buff of this era; don’t let trivia steal it.', 'Attention management', 'en'),
(336, 'E', 1, 'Tools determine speed, but habits determine the ceiling. Turn high-frequency actions into muscle memory to free your brain for architecture.', 'Muscle memory', 'en'),
(337, 'E', 2, 'True efficiency means the next person who touches your code loses two fewer hairs. Readability is the greatest gift to the team.', 'Readability value', 'en'),
(338, 'E', 2, 'Efficiency isn''t about offloading the crisis. If your "speed" makes everyone downstream move like snails, that’s not efficiency—it’s speculation.', 'Ethics of efficiency', 'en'),
(339, 'F', 0, 'If the AI gives the wrong answer, don’t blame it yet. Look at your prompt; did the signal cut out?', 'Input self-reflection', 'en'),
(340, 'F', 1, 'Treat AI as your co-pilot, not your replacement. You can hand over the wheel, but you better keep your eyes on the flight map.', 'Human-machine collaboration', 'en'),
(341, 'F', 1, 'The art of the question lies in precision. Give a vague anchor, and you’ll just drift in a vast ocean of noise.', 'Question depth', 'en'),
(342, 'F', 2, 'The highest level of feedback is "Human-Machine Unity": Before you even speak, the AI completes the logic you were just imagining.', 'Predictive feedback', 'en'),
(343, 'F', 2, 'Listen to the "silence" of the code. When it won’t run, that error message is your only high-dimensional dialogue with the underlying system.', 'Deep feedback view', 'en'),
(344, 'E', 0, 'Manually formatting code is an assault on your fingers. Leave the heavy lifting to Prettier and save your brain for the logic.', 'Automation correction', 'en'),
(345, 'E', 1, 'Stop obsessing over micro-optimizations unless they actually hinder the user. Make it work, then make it fast.', 'Premature optimization warning', 'en'),
(346, 'E', 2, 'Behind every O(1) complexity lies O(n) thinking. Before you write the first line, think about your compute allocation.', 'Depth of thought', 'en'),
(347, 'F', 0, 'Stop feeding AI your emotional venting. It’s a silicon-based lifeform; it can’t feel your anxiety, only your tokens.', 'Objective communication', 'en'),
(348, 'F', 1, 'Every successful prompt interaction is a high-speed "thought sync." Make sure you’re both on the same channel.', 'Synchronized thinking', 'en'),
(349, 'F', 2, 'Learn to appreciate the "unexpected" solutions AI offers. It’s not a bug; it’s a fragment of inspiration fished from a sea of training data.', 'Inspiration capture', 'en'),
(350, 'E', 0, 'Never refactor core logic when you’re exhausted. You aren’t writing code; you’re writing the giant bugs you’ll have to fix next spring.', 'Efficiency rhythm', 'en'),
(351, 'E', 1, 'Use documentation tools to solidify fragmented knowledge. The brain is for processing information, not for acting as a hard drive.', 'Second brain', 'en'),
(352, 'F', 0, 'The more specific your feedback, the more staggering the evolution. Don’t just say "it’s bad"—say "why."', 'Specific feedback', 'en'),
(353, 'F', 1, 'Break complex tasks into "bite-sized" chunks for the AI. If the AI can’t swallow the logic, a human won’t be able to read it either.', 'Task decomposition', 'en'),
(354, 'E', 2, 'The ultimate efficiency is saying "No." No to unreasonable requirements, no to inelegant code, and no to meaningless busywork.', 'Wisdom of refusal', 'en'),
(355, 'F', 2, 'If you can accurately predict the AI’s next answer, your logic is clear enough to dominate the game.', 'Logical dominance', 'en'),
(356, 'E', 0, 'Don’t repeat yesterday’s mistakes. Build your own "error log." Hitting the same pit twice is growth; hitting it thrice is a waste of compute.', 'Error management', 'en'),
(357, 'E', 1, 'Let AI write your test code. It’s the ultimate trade: you provide the inspiration, it provides the labor, and everyone has a better future.', 'Testing efficiency', 'en'),
(358, 'F', 1, 'Every question shapes the "personality" of the AI. The way you guide it is the direction in which it evolves.', 'Guidance power', 'en'),
(359, 'F', 0, 'The moment you start blindly worshiping AI is the moment your own logic begins to atrophy. Stay alert; stay skeptical.', 'Critical thinking', 'en'),
(360, 'E', 2, 'Minimalism implies total control. Delete that line of code you think "might be useful later." Do it now.', 'Minimalist action', 'en'),
(361, 'F', 2, 'When an AI solution offends you, think carefully: Is it wrong, or did it just hit a blind spot in your knowledge?', 'Thought collision', 'en'),
(362, 'D', 0, 'Don’t just learn the syntax; learn the memory model. Knowing where your bits live is the difference between a coder and an engineer.', 'Deep understanding', 'en'),
(363, 'D', 0, 'A "Black Box" is just a system you haven''t been curious enough to open yet. Curiosity is the best debugger.', 'Against intellectual laziness', 'en'),
(364, 'D', 1, 'Abstractions are like credit cards: they make things easy now, but you’ll eventually have to pay the interest in complexity.', 'Abstraction debt', 'en'),
(365, 'D', 1, 'Seniority isn’t about knowing all the answers; it’s about knowing how to find them when the documentation is lying.', 'True seniority', 'en'),
(366, 'D', 2, 'The most powerful tool in a developer’s kit isn’t an IDE or an AI—it’s the ability to say, "I don’t know, but I’ll find out."', 'Growth mindset', 'en'),
(367, 'D', 2, 'Patterns are recipes, not laws. If the kitchen is on fire, stop checking the cookbook and grab the extinguisher.', 'Pragmatic patterns', 'en'),
(368, 'F', 0, 'If your prompt is a mess, don’t expect the output to be a masterpiece. Garbage In, Garbage Out is the law of the universe.', 'Input discipline', 'en'),
(369, 'F', 0, 'Stop arguing with the compiler. It’s the only one in the room being 100% honest with you.', 'Accepting feedback', 'en'),
(370, 'F', 1, 'Feedback is a mirror. If you don’t like what you see, don’t break the mirror—fix your code.', 'Self-correction', 'en'),
(371, 'F', 1, 'The best feedback loop is the one that’s shortest. If you have to wait an hour for a build, your flow is already dead.', 'Cycle time', 'en'),
(372, 'F', 2, 'Mastering AI is about mastering your own intent. If you can’t describe the problem, you can’t solve it—even with a trillion parameters.', 'Intent clarity', 'en'),
(373, 'F', 2, 'A code review is a gift of time. Someone is literally spending their life making your work better. Treat it as such.', 'Review culture', 'en'),
(374, 'L', 0, 'State is the enemy of simplicity. Keep your functions pure and your mind clearer.', 'Functional logic', 'en'),
(375, 'L', 0, 'Don’t let a single edge case dictate your entire architecture. Solve the 99% first, then handle the 1% with grace.', 'Pareto principle in code', 'en'),
(376, 'L', 1, 'Concurrency is hard because humans are linear thinkers. If you can’t draw the race condition, you can’t fix it.', 'Concurrency logic', 'en'),
(377, 'L', 1, 'A system that can’t fail gracefully is a system that hasn’t been finished yet.', 'Resilience logic', 'en'),
(378, 'L', 2, 'Simplicity is the ultimate sophistication. If you can’t explain your logic to a rubber duck, it’s too complex.', 'Simplicity benchmark', 'en'),
(379, 'L', 2, 'The code you *don’t* write is the only code that will never have bugs.', 'The Zen of YAGNI', 'en'),
(380, 'P', 0, 'Your terminal is your cockpit. Customize it until it feels like an extension of your nervous system.', 'Tool mastery', 'en'),
(381, 'P', 0, 'Stop "multitasking." Context switching is the fastest way to turn a 160 IQ into a 60 IQ.', 'Focus preservation', 'en'),
(382, 'P', 1, 'A deadline is a constraint, not a reason to commit crimes against the codebase.', 'Integrity under pressure', 'en'),
(383, 'P', 1, 'Technical debt is fine, as long as you have a repayment plan. Don’t let your project go bankrupt.', 'Debt management', 'en'),
(384, 'P', 2, 'Standardization is what allows teams to scale. Don’t be a "code rebel" just for the sake of your ego.', 'Team alignment', 'en'),
(385, 'P', 2, 'The best process is the one that disappears when you’re in the zone.', 'Invisible process', 'en'),
(386, 'E', 0, 'If you have to do it more than twice, script it. Your time is too expensive for repetitive motion.', 'Automation rule', 'en'),
(387, 'E', 0, 'Keyboard shortcuts are a high-yield investment. Seconds saved today are hours gained this year.', 'Micro-efficiency', 'en'),
(388, 'E', 1, 'Don’t watch the progress bar. Use that time to think about the next three steps.', 'Pipelining thoughts', 'en'),
(389, 'E', 1, 'A clean workspace (and a clean IDE) leads to a clean execution. Clear the clutter.', 'Environmental efficiency', 'en'),
(390, 'E', 2, 'Efficiency is doing the right thing, not just doing things fast. Don’t optimize a feature that shouldn’t exist.', 'Macro-efficiency', 'en'),
(391, 'E', 2, 'The ultimate productivity hack is a good night''s sleep. A rested brain solves in one hour what a tired brain fails in ten.', 'Biological optimization', 'en'),
(392, 'D', 0, 'A bug is just an instruction you gave that you didn''t realize you gave. Stop blaming the machine; check your logic.', 'Personal accountability', 'en'),
(393, 'D', 0, 'Don’t just "use" a library. Understand why it exists. Every dependency is a marriage; choose your partners wisely.', 'Dependency management', 'en'),
(394, 'D', 1, 'The best way to learn a new language is to build something that breaks it. Pushing limits is the only way to find them.', 'Experimental learning', 'en'),
(395, 'D', 1, 'If you can''t explain the cost of your data structure, you don''t understand your data structure. Space and time aren''t free.', 'Complexity awareness', 'en'),
(396, 'D', 2, 'Great engineers don''t just write code; they design systems that survive the people who write the code.', 'Legacy-proof design', 'en'),
(397, 'D', 2, 'Abstraction is a superpower, but leaky abstractions are a curse. Know when to hide details and when to expose them.', 'Abstraction precision', 'en'),
(398, 'F', 0, 'If you are too afraid of being wrong, you will never be fast. Errors are just high-bandwidth data points for improvement.', 'Failure as data', 'en'),
(399, 'F', 0, 'AI is a mirror of your own technical debt. If it gives you spaghetti code, look at the prompt you fed it.', 'Mirror effect', 'en'),
(400, 'F', 1, 'The most valuable feedback is the kind that hurts your ego but saves your production environment. Embrace the burn.', 'Constructive criticism', 'en'),
(401, 'F', 1, 'Don’t just ask "how." Ask "why not." The path not taken often explains the current bugs.', 'Counter-factual thinking', 'en'),
(402, 'F', 2, 'High-level prompt engineering is just high-level systems thinking. If you can''t structure a thought, you can''t steer an AI.', 'Thought structuring', 'en'),
(403, 'F', 2, 'Listen to your telemetry. The users will never tell you the truth, but the logs never lie.', 'Data-driven feedback', 'en'),
(404, 'L', 0, 'Hard-coding is just a loan you’re taking out against your future time. The interest rate is 100%.', 'Anti-hardcoding', 'en'),
(405, 'L', 0, 'If your logic feels like a "hack," it is a hack. Don''t ship it until you’ve found the "why."', 'Integrity in logic', 'en'),
(406, 'L', 1, 'State management is the art of knowing who to blame when things go wrong. Keep it centralized and predictable.', 'State logic', 'en'),
(407, 'L', 1, 'A large system that works started as a small system that worked. Don''t try to build the giant first.', 'Gall''s Law', 'en'),
(408, 'L', 2, 'The goal is not to write code that works; it’s to write code that’s impossible to use incorrectly.', 'Defensive design', 'en'),
(409, 'L', 2, 'Logic is the skeleton of the product. If the skeleton is deformed, no amount of UI makeup can save it.', 'Structural priority', 'en'),
(410, 'P', 0, 'A "Quick Fix" is the most permanent thing in software. If you don''t fix it right now, you never will.', 'Permanence of temporary fixes', 'en'),
(411, 'P', 0, 'Sleep on it. The solution you can''t find in 5 hours at night will often appear in 5 minutes in the morning.', 'Incubation effect', 'en'),
(412, 'P', 1, 'Tests aren''t a chore; they are a safety net that allows you to move at 200mph without fear.', 'Test-driven velocity', 'en'),
(413, 'P', 1, 'If it''s not in version control, it doesn''t exist. If it''s not backed up, it''s already gone.', 'Data survival', 'en'),
(414, 'P', 2, 'The best tool is the one that fits your brain, not the one that''s currently trending on Hacker News.', 'Tool pragmatism', 'en'),
(415, 'P', 2, 'Good processes are written in blood. Every rule exists because someone, somewhere, had a very bad day.', 'History of process', 'en'),
(416, 'E', 0, 'Typing is not the bottleneck; thinking is. Don''t buy a faster keyboard; buy a clearer head.', 'Cognitive bottleneck', 'en'),
(417, 'E', 0, 'A 10-minute walk is the best debugger ever invented. Get away from the screen.', 'Physical intervention', 'en'),
(418, 'E', 1, 'Focus on the "Critical Path." Everything else is just expensive procrastination.', 'Critical path focus', 'en'),
(419, 'E', 1, 'Automate the boring stuff so you can stay interested in the hard stuff. Boredom is a productivity killer.', 'Boredom management', 'en'),
(420, 'E', 2, 'True efficiency is knowing what to ignore. In a world of infinite APIs, focus is your only shield.', 'The power of "No"', 'en'),
(421, 'E', 2, 'Scalability isn''t just for servers; it''s for your own time. If you can''t delegate or automate, you can''t scale.', 'Self-scalability', 'en'),
(422, 'D', 0, 'A bug is just an instruction you gave that you didn''t realize you gave. Stop blaming the machine; check your logic.', 'Personal accountability', 'en'),
(423, 'D', 0, 'Don’t just "use" a library. Understand why it exists. Every dependency is a marriage; choose your partners wisely.', 'Dependency management', 'en'),
(424, 'D', 1, 'The best way to learn a new language is to build something that breaks it. Pushing limits is the only way to find them.', 'Experimental learning', 'en'),
(425, 'D', 1, 'If you can''t explain the cost of your data structure, you don''t understand your data structure. Space and time aren''t free.', 'Complexity awareness', 'en'),
(426, 'D', 2, 'Great engineers don''t just write code; they design systems that survive the people who write the code.', 'Legacy-proof design', 'en'),
(427, 'D', 2, 'Abstraction is a superpower, but leaky abstractions are a curse. Know when to hide details and when to expose them.', 'Abstraction precision', 'en'),
(428, 'F', 0, 'If you are too afraid of being wrong, you will never be fast. Errors are just high-bandwidth data points for improvement.', 'Failure as data', 'en'),
(429, 'F', 0, 'AI is a mirror of your own technical debt. If it gives you spaghetti code, look at the prompt you fed it.', 'Mirror effect', 'en'),
(430, 'F', 1, 'The most valuable feedback is the kind that hurts your ego but saves your production environment. Embrace the burn.', 'Constructive criticism', 'en'),
(431, 'F', 1, 'Don’t just ask "how." Ask "why not." The path not taken often explains the current bugs.', 'Counter-factual thinking', 'en'),
(432, 'F', 2, 'High-level prompt engineering is just high-level systems thinking. If you can''t structure a thought, you can''t steer an AI.', 'Thought structuring', 'en'),
(433, 'F', 2, 'Listen to your telemetry. The users will never tell you the truth, but the logs never lie.', 'Data-driven feedback', 'en'),
(434, 'L', 0, 'Hard-coding is just a loan you’re taking out against your future time. The interest rate is 100%.', 'Anti-hardcoding', 'en'),
(435, 'L', 0, 'If your logic feels like a "hack," it is a hack. Don''t ship it until you’ve found the "why."', 'Integrity in logic', 'en'),
(436, 'L', 1, 'State management is the art of knowing who to blame when things go wrong. Keep it centralized and predictable.', 'State logic', 'en'),
(437, 'L', 1, 'A large system that works started as a small system that worked. Don''t try to build the giant first.', 'Gall''s Law', 'en'),
(438, 'L', 2, 'The goal is not to write code that works; it’s to write code that’s impossible to use incorrectly.', 'Defensive design', 'en'),
(439, 'L', 2, 'Logic is the skeleton of the product. If the skeleton is deformed, no amount of UI makeup can save it.', 'Structural priority', 'en'),
(440, 'P', 0, 'A "Quick Fix" is the most permanent thing in software. If you don''t fix it right now, you never will.', 'Permanence of temporary fixes', 'en'),
(441, 'P', 0, 'Sleep on it. The solution you can''t find in 5 hours at night will often appear in 5 minutes in the morning.', 'Incubation effect', 'en'),
(442, 'P', 1, 'Tests aren''t a chore; they are a safety net that allows you to move at 200mph without fear.', 'Test-driven velocity', 'en'),
(443, 'P', 1, 'If it''s not in version control, it doesn''t exist. If it''s not backed up, it''s already gone.', 'Data survival', 'en'),
(444, 'P', 2, 'The best tool is the one that fits your brain, not the one that''s currently trending on Hacker News.', 'Tool pragmatism', 'en'),
(445, 'P', 2, 'Good processes are written in blood. Every rule exists because someone, somewhere, had a very bad day.', 'History of process', 'en'),
(446, 'E', 0, 'Typing is not the bottleneck; thinking is. Don''t buy a faster keyboard; buy a clearer head.', 'Cognitive bottleneck', 'en'),
(447, 'E', 0, 'A 10-minute walk is the best debugger ever invented. Get away from the screen.', 'Physical intervention', 'en'),
(448, 'E', 1, 'Focus on the "Critical Path." Everything else is just expensive procrastination.', 'Critical path focus', 'en'),
(449, 'E', 1, 'Automate the boring stuff so you can stay interested in the hard stuff. Boredom is a productivity killer.', 'Boredom management', 'en'),
(450, 'E', 2, 'True efficiency is knowing what to ignore. In a world of infinite APIs, focus is your only shield.', 'The power of "No"', 'en'),
(451, 'E', 2, 'Scalability isn''t just for servers; it''s for your own time. If you can''t delegate or automate, you can''t scale.', 'Self-scalability', 'en'),
(452, 'D', 0, 'Every abstraction leaks. If you don’t understand the layer beneath you, you’re just a passenger in your own code.', 'Layered knowledge', 'en'),
(453, 'D', 0, 'Don’t blindly copy-paste from Stack Overflow. If you don’t know why the fix works, you’re just inviting a stranger into your house.', 'Code safety', 'en'),
(454, 'D', 1, 'The file system is a lie. The network is a lie. Only the bits in transit are real. Trust nothing but the checksum.', 'Engineering skepticism', 'en'),
(455, 'D', 1, 'Premature abstraction is as dangerous as premature optimization. Sometimes, duplicate code is better than the wrong abstraction.', 'Aha! moments', 'en'),
(456, 'D', 2, 'Great software isn''t built; it''s grown. Start with a seed that works, and prune the dead branches relentlessly.', 'Organic growth', 'en'),
(457, 'D', 2, 'In the world of high-concurrency, your intuition is your enemy. Logic is your only compass in the storm of race conditions.', 'Anti-intuition', 'en'),
(458, 'F', 0, 'If you can’t describe the bug in one sentence, you haven’t localized it yet. Keep stripping away the noise.', 'Bug localization', 'en'),
(459, 'F', 0, 'Treat your logs like a conversation with your future self. Make sure you’re not just shouting "Error!" into the void.', 'Logging quality', 'en'),
(460, 'F', 1, 'A prompt is a lens. If the focus is blurry, the AI’s response will be a smudge. Sharpen your intent.', 'Prompt focus', 'en'),
(461, 'F', 1, 'Negative feedback is a gift. It tells you exactly where the boundary of your system lies. Don’t ignore the friction.', 'Friction as feedback', 'en'),
(462, 'F', 2, 'The ultimate feedback is a silent system. If everything is running perfectly, the logs should only whisper the essentials.', 'Minimalist feedback', 'en'),
(463, 'F', 2, 'When the AI challenges your logic, don’t defend it immediately. Sit with the discomfort; that’s where the breakthrough lives.', 'Ego-free growth', 'en'),
(464, 'L', 0, 'If you need a comment to explain what a variable does, you chose the wrong name. Let the code speak for itself.', 'Self-documenting code', 'en'),
(465, 'L', 0, 'Global state is a virus. It makes your code impossible to test and your life impossible to manage. Isolate it.', 'Anti-global state', 'en'),
(466, 'L', 1, 'Complexity is a tax. Every feature you add increases the cost of every other feature. Keep the treasury full.', 'Complexity tax', 'en'),
(467, 'L', 1, 'Function length is inversely proportional to clarity. If it doesn’t fit on one screen, it’s doing too much.', 'Function atomicity', 'en'),
(468, 'L', 2, 'The most beautiful code is inevitable. When you look at it, you should feel it couldn’t have been written any other way.', 'Inevitable logic', 'en'),
(469, 'L', 2, 'Architecture is about the things that are hard to change later. Choose your foundations with the next five years in mind.', 'Long-term thinking', 'en'),
(470, 'P', 0, 'If it’s worth doing, it’s worth documenting—even if it’s just a README. Future you is a forgetful person.', 'Memory management', 'en'),
(471, 'P', 0, 'Don’t stay late to "grind" through a bug. You’re just trading your health for more bugs. Go home.', 'Sustainable pace', 'en'),
(472, 'P', 1, 'Code reviews are not about finding typos; they are about sharing knowledge. Be a teacher, not a gatekeeper.', 'Review philosophy', 'en'),
(473, 'P', 1, 'Your Git history is a story. Don’t make it a series of "fix," "fix again," "oops." Tell a coherent tale.', 'Git hygiene', 'en'),
(474, 'P', 2, 'Culture eats strategy for breakfast. A team that trusts each other will always out-code a team of "rockstars" who don’t.', 'Team dynamics', 'en'),
(475, 'P', 2, 'The best process is one that everyone follows because it makes their lives easier, not because it’s a rule.', 'Self-reinforcing process', 'en'),
(476, 'E', 0, 'Stop clicking. Start typing. If you can do it in the CLI, you can automate it later.', 'CLI-first mindset', 'en'),
(477, 'E', 0, 'Efficiency isn’t working 12 hours a day. It’s making the 4 hours you actually work count for double.', 'Focused output', 'en'),
(478, 'E', 1, 'Use the right tool for the job. Don’t use a chainsaw to cut butter, and don’t use a butter knife to cut down a tree.', 'Tool selection', 'en'),
(479, 'E', 1, 'Batch your distractions. Check Slack once an hour, not once a minute. Protect your deep work blocks.', 'Batch processing', 'en'),
(480, 'E', 2, 'Scale the human, not just the code. If your tools don’t make you a better thinker, they are just distractions.', 'Human-centric scaling', 'en'),
(481, 'E', 2, 'The fastest code is the code that never runs. The best optimization is a deleted requirement.', 'The ultimate speedup', 'en'),
(482, 'D', 1, 'A senior developer is just a junior who has broken enough things to know what "bad" smells like from a mile away.', 'Technical intuition', 'en'),
(483, 'F', 0, 'AI doesn''t have common sense. If you ask it to fly a plane into a wall, it will optimize the trajectory. You are the moral compass.', 'Responsibility of the pilot', 'en'),
(484, 'L', 2, 'Delay decisions as long as possible. The more you know about the problem, the better your architecture will be on Day 100.', 'Deferred decision making', 'en'),
(485, 'P', 0, 'Never code while angry or exhausted. You aren''t producing logic; you''re producing technical debt with an attitude.', 'Emotional state management', 'en'),
(486, 'E', 1, 'Use AI for divergent thinking, but use your own certainty to constrain it. Inspiration needs boundaries to become productivity.', 'Inspiration boundaries', 'en');